# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: ihmcallister/but-why-vikings
  branch: main
  site_domain: butwhyvikings.netlify.app
  squash_merges: true
publish_mode: editorial_workflow
site_url: https://butwhyvikings.netlify.app/
media_folder: site/static/img
